import { REST_PROCESSOR_HIGHLIGHTS } from "./rest-highlights.js";
import { buildGapRows, buildGapSummary } from "./gap-manifest.js";
import type { GapRow, ImplementationStatus, ProcessorInfo } from "./types.js";

function commandStatusLabel(
  status: ImplementationStatus,
  command: string,
): string {
  if (status.implementedCommands.includes(command)) {
    return "Implemented";
  }
  if (status.specifiedCommands.includes(command)) {
    return "Specified, **not implemented**";
  }
  return "Not specified";
}

function listScopeProcessors(processors: readonly ProcessorInfo[]): ProcessorInfo[] {
  return processors.filter((processor) => processor.groupId === "scan.scope");
}

function listAssemblyProcessors(processors: readonly ProcessorInfo[]): ProcessorInfo[] {
  return processors.filter((processor) => processor.groupId.startsWith("scan.source.assembly"));
}

function listRestProcessors(processors: readonly ProcessorInfo[]): ProcessorInfo[] {
  return processors.filter(
    (processor) =>
      (processor.groupId === "scan.source.java.rest" ||
        processor.groupId === "scan.source.kotlin.rest") &&
      processor.artifactId.startsWith("controller-"),
  );
}

function listRestClientProcessors(processors: readonly ProcessorInfo[]): ProcessorInfo[] {
  return processors.filter(
    (processor) =>
      (processor.groupId === "scan.source.java.rest" ||
        processor.groupId === "scan.source.kotlin.rest") &&
      processor.artifactId.startsWith("client-"),
  );
}

function slotLayer(kind: string): "technology" | "application" | "other" {
  const normalized = kind.toLowerCase();
  if (normalized.startsWith("technology/")) {
    return "technology";
  }
  if (normalized.startsWith("application/")) {
    return "application";
  }
  return "other";
}

function uniqueSlotLabels(
  status: ImplementationStatus,
  layer: "technology" | "application",
): string[] {
  const labels = new Map<string, string>();
  for (const slot of status.elementSlots) {
    if (!status.implementedElementSlotIds.has(slot.slotId)) {
      continue;
    }
    if (slotLayer(slot.kind) !== layer) {
      continue;
    }
    if (!labels.has(slot.slotId)) {
      labels.set(slot.slotId, slot.label);
    }
  }
  return [...labels.values()].sort();
}

function renderRestSection(processors: readonly ProcessorInfo[]): string[] {
  const lines = [
    "- **REST controllers (Java/Kotlin)** — annotation-based and functional routing:",
  ];

  for (const processor of processors) {
    const highlights = REST_PROCESSOR_HIGHLIGHTS[processor.coordinate];
    if (highlights) {
      for (const highlight of highlights) {
        lines.push(`  - ${highlight}`);
      }
      continue;
    }
    lines.push(`  - ${processor.description}`);
  }

  return [...new Set(lines)];
}

function renderRestClientSection(processors: readonly ProcessorInfo[]): string[] {
  const lines = [
    "- **REST clients (Java/Kotlin)** — declarative and programmatic HTTP clients:",
  ];

  for (const processor of processors) {
    const highlights = REST_PROCESSOR_HIGHLIGHTS[processor.coordinate];
    if (highlights) {
      for (const highlight of highlights) {
        lines.push(`  - ${highlight}`);
      }
      continue;
    }
    lines.push(`  - ${processor.description}`);
  }

  return [...new Set(lines)];
}

function renderDiscoveryOutputFiles(status: ImplementationStatus): string {
  const files = ["manifest.json", "repositories.json"];
  if (status.scanEntityTypes.has("ApplicationModule")) {
    files.push("application-modules.json");
  }
  if (status.scanEntityTypes.has("ApplicationModuleDependency")) {
    files.push("application-module-dependencies.json");
  }
  if (status.scanEntityTypes.has("RestController")) {
    files.push("rest-controllers.json");
  }
  if (status.scanEntityTypes.has("RestClient")) {
    files.push("rest-clients.json");
  }
  return files.join(", ");
}

export function renderWhatWorksToday(status: ImplementationStatus): string {
  const commands = [...status.specifiedCommands, ...status.implementedCommands]
    .filter((command, index, all) => all.indexOf(command) === index)
    .sort();

  const scopeProcessors = listScopeProcessors(status.processors);
  const assemblyProcessors = listAssemblyProcessors(status.processors);
  const restProcessors = listRestProcessors(status.processors);
  const restClientProcessors = listRestClientProcessors(status.processors);
  const technologySlots = uniqueSlotLabels(status, "technology");
  const applicationSlots = uniqueSlotLabels(status, "application");

  const lines: string[] = [
    "## What works today",
    "",
    "_Auto-generated by `npm run readme:sync`. Do not edit manually — update code/specs and re-run the script._",
    "",
    "### Commands",
    "",
    "| Command | Status |",
    "| ------- | ------ |",
  ];

  for (const command of commands) {
    lines.push(`| \`${command}\` | ${commandStatusLabel(status, command)} |`);
  }

  lines.push("", "### `scan` — discovery-model", "", "Built-in processors discover:", "");

  if (scopeProcessors.length > 0) {
    const scopeNames = scopeProcessors.map((processor) => `\`${processor.artifactId}\``).join(", ");
    lines.push(
      `- **Repositories** — ${scopeNames} (\`scan.scope\`)`,
    );
  }

  if (assemblyProcessors.length > 0) {
    const buildSystems = assemblyProcessors
      .map((processor) => {
        if (processor.groupId.includes(".maven")) {
          return "Maven";
        }
        if (processor.groupId.includes(".gradle")) {
          return "Gradle";
        }
        if (processor.groupId.includes(".npm")) {
          return "npm";
        }
        return processor.artifactId;
      })
      .join(", ");
    lines.push(
      `- **Application modules** — ${buildSystems} (including workspaces where applicable) with inter-module dependencies (\`scan.source.assembly\`)`,
    );
  }

  if (restProcessors.length > 0) {
    lines.push(...renderRestSection(restProcessors));
  }

  if (restClientProcessors.length > 0) {
    lines.push(...renderRestClientSection(restClientProcessors));
  }

  lines.push(
    "",
    `Output is a directory of JSON files (${renderDiscoveryOutputFiles(status)}, …) validated against JSON Schema in the specifications repo.`,
    "",
    "### `generate` — ArchiMate model",
    "",
    "From discovery-model, built-in processors currently materialise these **element slots** (see [generated-element-slots](../documentation/specifications/archimate-model/generated-element-slots.md)):",
    "",
  );

  if (technologySlots.length > 0) {
    lines.push("**Technology layer**", "");
    for (const label of technologySlots) {
      lines.push(`- ${label}`);
    }
    lines.push("");
  }

  if (applicationSlots.length > 0) {
    lines.push("**Application layer**", "");
    for (const label of applicationSlots) {
      lines.push(`- ${label}`);
    }
    lines.push("");
  }

  lines.push(
    "The result is a plain XML `.archimate` file compatible with Archi 5.x.",
    "",
    "### Platform mechanics (in all commands)",
    "",
    "- Structured file logging and optional stderr mirror",
    "- Optional profiling (`code2archi-profile-<command>-<timestamp>.json`)",
    "- Worker-thread parallelism with processor registry and CLI filters",
    "- Idempotent element generation with stable `c2a:Id` custom properties",
  );

  return lines.join("\n");
}

function renderGapTable(rows: readonly GapRow[]): string[] {
  const lines = [
    "| Area | Product intent | Current state |",
    "| ---- | -------------- | ------------- |",
  ];

  for (const row of rows) {
    const intent = row.intent.replace(/\|/g, "\\|");
    let currentState = row.currentState;
    if (row.capabilityLink) {
      const linkLabel = row.capabilityLink.split("/").pop()?.replace(".md", "") ?? "capability";
      if (!row.complete && currentState === "Not implemented") {
        currentState = `Not implemented (capability: [${linkLabel}](${row.capabilityLink}))`;
      }
    }
    currentState = currentState.replace(/\|/g, "\\|");
    lines.push(`| **${row.area}** | ${intent} | ${currentState} |`);
  }

  return lines;
}

export function renderGapVsProductIntent(status: ImplementationStatus): string {
  const rows = buildGapRows(status);
  const summary = buildGapSummary(status, rows);

  const lines = [
    "## Gap vs product intent",
    "",
    "_Auto-generated by `npm run readme:sync`. Do not edit manually — update code/specs and re-run the script._",
    "",
    "The README above describes the **current slice** of the vision. The table below summarises what is planned but not yet delivered.",
    "",
    ...renderGapTable(rows),
    "",
    summary,
  ];

  return lines.join("\n");
}

export function renderReadmeStatusSections(status: ImplementationStatus): {
  whatWorksToday: string;
  gapVsProductIntent: string;
} {
  return {
    whatWorksToday: renderWhatWorksToday(status),
    gapVsProductIntent: renderGapVsProductIntent(status),
  };
}
