import { ModulesAndDependenciesProcessor as GradleModulesAndDependenciesProcessor } from "../../processors/scan/extract/assembly/gradle/modules-and-dependencies-processor.js";
import { ModulesAndDependenciesProcessor as MavenModulesAndDependenciesProcessor } from "../../processors/scan/extract/assembly/maven/modules-and-dependencies-processor.js";
import { ModulesAndDependenciesProcessor as NpmModulesAndDependenciesProcessor } from "../../processors/scan/extract/assembly/npm/modules-and-dependencies-processor.js";
import { AppComponentsFromModulesProcessor } from "../../processors/generate/elements/application/app-components-from-modules-processor.js";
import { SyssoftForBuildSystemsAndRuntimesProcessor } from "../../processors/generate/elements/technology/syssoft-for-build-systems-and-runtimes-processor.js";
import { SyssoftForNoBuildOrRuntimeToolsProcessor } from "../../processors/generate/elements/technology/syssoft-for-no-build-or-runtime-tools-processor.js";
import { CodeRepositoriesProcessor } from "../../processors/generate/elements/technology/code-repositories-processor.js";
import { GitRepositoriesProcessor } from "../../processors/scan/scope/git-repositories-processor.js";
import { UnversionedFoldersProcessor } from "../../processors/scan/scope/unversioned-folders-processor.js";
import { processorRegistry } from "./processor-registry.js";

processorRegistry.register(new GitRepositoriesProcessor());
processorRegistry.register(new UnversionedFoldersProcessor());
processorRegistry.register(new MavenModulesAndDependenciesProcessor());
processorRegistry.register(new GradleModulesAndDependenciesProcessor());
processorRegistry.register(new NpmModulesAndDependenciesProcessor());
processorRegistry.register(new CodeRepositoriesProcessor());
processorRegistry.register(new SyssoftForBuildSystemsAndRuntimesProcessor());
processorRegistry.register(new SyssoftForNoBuildOrRuntimeToolsProcessor());
processorRegistry.register(new AppComponentsFromModulesProcessor());
