import { NodejsRestClientProgrammaticProcessor } from "../../processors/scan/extract/nodejs/rest/client-programmatic-processor.js";
import { NodejsRestControllerDeclarativeProcessor } from "../../processors/scan/extract/nodejs/rest/controller-declarative-processor.js";
import { NodejsRestControllerFunctionalRouterProcessor } from "../../processors/scan/extract/nodejs/rest/controller-functional-router-processor.js";
import { NodejsRestControllerNextjsAppRouterProcessor } from "../../processors/scan/extract/nodejs/rest/controller-nextjs-app-router-processor.js";
import { NodejsDirectRestRequestsServingProcessor as ScanNodejsDirectRestRequestsServingProcessor } from "../../processors/scan/transform/nodejs/direct-rest-requests-serving-processor.js";
import { JavaRestControllerAnnotationBasedProcessor } from "../../processors/scan/extract/java/rest/controller-annotation-based-processor.js";
import { JavaRestControllerFunctionalRouterBasedProcessor } from "../../processors/scan/extract/java/rest/controller-functional-router-based-processor.js";
import { KotlinRestControllerAnnotationBasedProcessor } from "../../processors/scan/extract/kotlin/rest/controller-annotation-based-processor.js";
import { KotlinRestControllerKtorAndRouterBasedProcessor } from "../../processors/scan/extract/kotlin/rest/controller-ktor-and-router-based-processor.js";
import { JavaRestClientDeclarativeProcessor } from "../../processors/scan/extract/java/rest/client-declarative-processor.js";
import { JavaRestClientProgrammaticProcessor } from "../../processors/scan/extract/java/rest/client-programmatic-processor.js";
import { KotlinRestClientDeclarativeProcessor } from "../../processors/scan/extract/kotlin/rest/client-declarative-processor.js";
import { KotlinRestClientProgrammaticProcessor } from "../../processors/scan/extract/kotlin/rest/client-programmatic-processor.js";
import { ModulesAndDependenciesProcessor as GradleModulesAndDependenciesProcessor } from "../../processors/scan/extract/assembly/gradle/modules-and-dependencies-processor.js";
import { ModulesAndDependenciesProcessor as MavenModulesAndDependenciesProcessor } from "../../processors/scan/extract/assembly/maven/modules-and-dependencies-processor.js";
import { ModulesAndDependenciesProcessor as NpmModulesAndDependenciesProcessor } from "../../processors/scan/extract/assembly/npm/modules-and-dependencies-processor.js";
import { AppComponentsFromModulesProcessor } from "../../processors/generate/elements/application/app-components-from-modules-processor.js";
import { ControllersProcessor } from "../../processors/generate/elements/application/rest/controllers-processor.js";
import { ClientsProcessor } from "../../processors/generate/elements/application/rest/clients-processor.js";
import { ApiContractsAndAssignmentsProcessor } from "../../processors/generate/elements/application/rest/api-contracts-and-assignments-processor.js";
import { DirectRestRequestsServingProcessor } from "../../processors/generate/elements/application/rest/direct-rest-requests-serving-processor.js";
import { ClientsToControllersLinksProcessor as ScanClientsToControllersLinksProcessor } from "../../processors/scan/transform/rest/clients-to-controllers-links-processor.js";
import { SyssoftForBuildSystemsAndRuntimesProcessor } from "../../processors/generate/elements/technology/syssoft-for-build-systems-and-runtimes-processor.js";
import { SyssoftForNoBuildOrRuntimeToolsProcessor } from "../../processors/generate/elements/technology/syssoft-for-no-build-or-runtime-tools-processor.js";
import { CodeRepositoriesProcessor } from "../../processors/generate/elements/technology/code-repositories-processor.js";
import { GitRepositoriesProcessor } from "../../processors/scan/scope/git-repositories-processor.js";
import { UnversionedFoldersProcessor } from "../../processors/scan/scope/unversioned-folders-processor.js";
import { processorRegistry } from "./processor-registry.js";

processorRegistry.register(new GitRepositoriesProcessor());
processorRegistry.register(new UnversionedFoldersProcessor());
processorRegistry.register(new MavenModulesAndDependenciesProcessor());
processorRegistry.register(new GradleModulesAndDependenciesProcessor());
processorRegistry.register(new NpmModulesAndDependenciesProcessor());
processorRegistry.register(new JavaRestControllerAnnotationBasedProcessor());
processorRegistry.register(new JavaRestControllerFunctionalRouterBasedProcessor());
processorRegistry.register(new KotlinRestControllerAnnotationBasedProcessor());
processorRegistry.register(new KotlinRestControllerKtorAndRouterBasedProcessor());
processorRegistry.register(new JavaRestClientDeclarativeProcessor());
processorRegistry.register(new JavaRestClientProgrammaticProcessor());
processorRegistry.register(new KotlinRestClientDeclarativeProcessor());
processorRegistry.register(new KotlinRestClientProgrammaticProcessor());
processorRegistry.register(new NodejsRestControllerFunctionalRouterProcessor());
processorRegistry.register(new NodejsRestControllerDeclarativeProcessor());
processorRegistry.register(new NodejsRestControllerNextjsAppRouterProcessor());
processorRegistry.register(new NodejsRestClientProgrammaticProcessor());
processorRegistry.register(new CodeRepositoriesProcessor());
processorRegistry.register(new SyssoftForBuildSystemsAndRuntimesProcessor());
processorRegistry.register(new SyssoftForNoBuildOrRuntimeToolsProcessor());
processorRegistry.register(new AppComponentsFromModulesProcessor());
processorRegistry.register(new ControllersProcessor());
processorRegistry.register(new ClientsProcessor());
processorRegistry.register(new ScanClientsToControllersLinksProcessor());
processorRegistry.register(new ScanNodejsDirectRestRequestsServingProcessor());
processorRegistry.register(new DirectRestRequestsServingProcessor());
processorRegistry.register(new ApiContractsAndAssignmentsProcessor());
