import { AnnotationBasedProcessor } from "../../processors/scan.source/annotation-based-processor.js";
import { FunctionalRouterBasedProcessor } from "../../processors/scan.source/functional-router-based-processor.js";
import { KotlinAnnotationBasedProcessor } from "../../processors/scan.source/kotlin-annotation-based-processor.js";
import { KotlinKtorAndRouterBasedProcessor } from "../../processors/scan.source/kotlin-ktor-and-router-based-processor.js";
import { JavaDeclarativeRestClientProcessor } from "../../processors/scan.source/java-declarative-rest-client-processor.js";
import { JavaProgrammaticRestClientProcessor } from "../../processors/scan.source/java-programmatic-rest-client-processor.js";
import { KotlinDeclarativeRestClientProcessor } from "../../processors/scan.source/kotlin-declarative-rest-client-processor.js";
import { KotlinProgrammaticRestClientProcessor } from "../../processors/scan.source/kotlin-programmatic-rest-client-processor.js";
import { GradleModulesAndDependenciesProcessor } from "../../processors/scan.source/gradle-modules-and-dependencies-processor.js";
import { MavenModulesAndDependenciesProcessor } from "../../processors/scan.source/maven-modules-and-dependencies-processor.js";
import { NpmModulesAndDependenciesProcessor } from "../../processors/scan.source/npm-modules-and-dependencies-processor.js";
import { ApplicationComponentsFromModulesProcessor } from "../../processors/generate.elements.application/application-components-from-modules-processor.js";
import { ControllersProcessor } from "../../processors/generate.elements.application.rest/controllers-processor.js";
import { ClientsAndDeclaredContractsProcessor } from "../../processors/generate.elements.application.rest/clients-and-declared-contracts-processor.js";
import { DeclaredApiContractsProcessor } from "../../processors/generate.elements.application.rest/declared-api-contracts-processor.js";
import { InferredApiContractsProcessor } from "../../processors/generate.elements.application.rest/inferred-api-contracts-processor.js";
import { ModulesBuildSystemsAndRuntimesProcessor } from "../../processors/generate.elements.technology/modules-build-systems-and-runtimes-processor.js";
import { NoBuildOrRuntimeToolsProcessor } from "../../processors/generate.elements.technology/no-build-or-runtime-tools-processor.js";
import { RepositoriesProcessor } from "../../processors/generate.elements.technology/repositories-processor.js";
import { GitReposProcessor } from "../../processors/scan.scope/git-repos-processor.js";
import { UnversionedFoldersProcessor } from "../../processors/scan.scope/unversioned-folders-processor.js";
import { processorRegistry } from "./processor-registry.js";

processorRegistry.register(new GitReposProcessor());
processorRegistry.register(new UnversionedFoldersProcessor());
processorRegistry.register(new MavenModulesAndDependenciesProcessor());
processorRegistry.register(new GradleModulesAndDependenciesProcessor());
processorRegistry.register(new NpmModulesAndDependenciesProcessor());
processorRegistry.register(new AnnotationBasedProcessor());
processorRegistry.register(new FunctionalRouterBasedProcessor());
processorRegistry.register(new KotlinAnnotationBasedProcessor());
processorRegistry.register(new KotlinKtorAndRouterBasedProcessor());
processorRegistry.register(new JavaDeclarativeRestClientProcessor());
processorRegistry.register(new JavaProgrammaticRestClientProcessor());
processorRegistry.register(new KotlinDeclarativeRestClientProcessor());
processorRegistry.register(new KotlinProgrammaticRestClientProcessor());
processorRegistry.register(new RepositoriesProcessor());
processorRegistry.register(new ModulesBuildSystemsAndRuntimesProcessor());
processorRegistry.register(new NoBuildOrRuntimeToolsProcessor());
processorRegistry.register(new ApplicationComponentsFromModulesProcessor());
processorRegistry.register(new ControllersProcessor());
processorRegistry.register(new DeclaredApiContractsProcessor());
processorRegistry.register(new ClientsAndDeclaredContractsProcessor());
processorRegistry.register(new InferredApiContractsProcessor());
